# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c20401be714a04e57c596fbcd9a9d200553a3bd0f9b1a3a5d2a85315bc13e2c651f99b326efe3c0d281d1261f7b5a83281a4ac48e46b3423abf7e70d2dedc12

test:
  secret_key_base: dc55f746d1d277424a21729b500a84760670c5a8d9815b8dfee1ab15bbfa24c5e0c0ba97db871f974065b1c711f0d6934994e06988d3e53d72311face89dd364

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
